Repository HanRiverVue/HanRiver, pull requests merged in 2025-02, with the labels that each got.

#106 feat: 마이페이지 수정 토스트 메시지 적용
  src/components/UserProfileModal.vue
  src/layout/header/components/LoggedInRight.vue
  src/pages/EditProfilePage/EditProfilePage.vue
  src/pages/EditProfilePage/components/DefaultInformation.vue
  src/pages/Mypage/MyPage.vue
  src/pages/RecruitPostDetailPage/RecruitPostDetailPage.vue
  src/pages/RecruitPostDetailPage/components/PostApplyList.vue
  src/pages/RecruitPostDetailPage/components/PostComment.vue
  src/pages/UserPage/UserPage.vue
  src/stores/user.js
  src/utils/toast.js
Labels: ✨Feature

#109 fix: 온보딩 버튼 비활, 완료 모달 라우트 수정
  src/pages/OnboardPage/OnboardPage.vue
  src/pages/OnboardPage/components/OnboardStep2.vue
  src/pages/OnboardPage/components/OnboardingCompleteModal.vue
Labels: 🐞 Bug

#111 fix : 각종 페이지 보완
  src/App.vue
  src/api/supabase/notifications.js
  src/api/supabase/post.js
  src/api/supabase/user.js
  src/components/UserProfileModal.vue
  src/pages/MainPage/MainPage.vue
  src/pages/MainPage/components/PostSection.vue
  src/pages/MainPage/components/SwipeablePostSection.vue
  src/pages/Mypage/components/LargePostCard.vue
  src/pages/Mypage/components/MyBookmark.vue
  src/pages/Mypage/components/MyInfo.vue
  src/pages/Mypage/components/MyRecruitmentList.vue
  src/pages/Mypage/components/MyRequestList.vue
  src/pages/PostListPage/PostListPage.vue
  src/pages/UserPage/components/UserRecruitmentList.vue
  src/router/index.js
  src/stores/user.js
  src/utils/usePagination.js
Labels: 🐞 Bug, 🔨 Refactor

#116 fix: 신청목록 필터링 안되는 오류 수정
  src/api/supabase/notifications.js
  src/api/supabase/post.js
  src/layout/header/components/LoggedInRight.vue
  src/pages/Mypage/components/LargePostCard.vue
  src/pages/Mypage/components/MyRequestList.vue
  src/pages/PostListPage/PostListPage.vue
Labels: 🐞 Bug

#115 fix: 프로필 수정 이후 반영이 안되는 문제 해결
  src/pages/EditProfilePage/EditProfilePage.vue
  src/pages/Mypage/MyPage.vue
  src/pages/Mypage/components/MyInfo.vue
Labels: 🐞 Bug

#104 ✨ feat: 상세페이지 좋아요, 북마크 구현 신청목록에서 모든 게시물 신청이 나오는 문제 수정, 모집 마감하기 구현
  jsconfig.json
  src/api/supabase/apply.js
  src/api/supabase/like_and_bookmark.js
  src/api/supabase/post_editor.js
  src/assets/icons/index.js
  src/pages/RecruitPostDetailPage/RecruitPostDetailPage.vue
  src/pages/RecruitPostDetailPage/components/PostApplyList.vue
  src/pages/RecruitPostDetailPage/components/PostComment.vue
  src/pages/RecruitPostDetailPage/components/PostSideBar.vue
Labels: 🐞 Bug, ✨Feature

#119 fix: 마이페이지 글자 수 제한 설정 누락 추가
  src/api/supabase/notifications.js
  src/layout/header/components/LoggedInRight.vue
  src/pages/EditProfilePage/components/DefaultInformation.vue
  src/pages/EditProfilePage/components/ProfileIntroduction.vue
  src/pages/Mypage/MyPage.vue
  src/pages/Mypage/components/MyInfo.vue
  src/stores/notificaionModal.js
Labels: 🐞 Bug

#120 ✨ feat: 삭제된 게시물에 들어가면 notfound 출력
  src/pages/RecruitPostDetailPage/RecruitPostDetailPage.vue
  src/pages/RecruitPostDetailPage/components/NotFound.vue
  src/pages/RecruitPostDetailPage/components/PostApplyList.vue
  src/pages/RecruitPostDetailPage/components/PostSideBar.vue
Labels: ✨Feature

#129 fix: 필터링 관련 오류 최종수정
  src/pages/Mypage/components/LargePostCard.vue
  src/pages/Mypage/components/MyBookmark.vue
  src/pages/Mypage/components/MyRecruitmentList.vue
  src/pages/UserPage/components/UserRecruitmentList.vue
Labels: 🐞 Bug

#147 bug: 배포시 새로고침 오류 수정
  public/_redirects
Labels: 🐞 Bug
