Repository HanRiverVue/HanRiver, pull requests merged in 2025-01, with the labels that each got.

#7 📝chore: 패키지 설치 및 기초 세팅
  package.json
  pnpm-lock.yaml
  postcss.config.js
  src/App.vue
  src/api/.txt
  src/api/axiosInstance.js
  src/config/supabase.js
  src/main.js
  src/styles/index.css
  src/styles/tailwind.css
  tailwind.config.js
Labels: ⚙ Chore

#15 ✨ feat: 수파베이스 알림, 좋아요, 북마크, 신청하기 api 구현
  src/api/apply.js
  src/api/bookmark.js
  src/api/like.js
  src/api/notifications.js
Labels: ✨Feature

#18 🚨fix : 수퍼베이스 게시물, 댓글, 검색 코드 수정
  src/App.vue
  src/api/post.js
  src/api/post_editor.js
  src/pages/test_api_page_hw/CommentEdit.vue
  src/pages/test_api_page_hw/Post.vue
  src/pages/test_api_page_hw/PostEdit.vue
Labels: 🐞 Bug

#19 💄 style: 스타일 가이드 세팅
  index.html
  package-lock.json
  pnpm-lock.yaml
  src/styles/index.css
  src/styles/tailwind.css
  src/styles/typography.css
  tailwind.config.js
Labels: 🎨 Design

#32 style: 공통 컴포넌트 (스킬 뱃지, 포지션 버튼, 상태 뱃지) 퍼블리싱
  package.json
  pnpm-lock.yaml
  src/components/.txt
  src/components/PositionSelectButton.vue
  src/components/SkillBadge.vue
  src/components/SkillSelectButton.vue
  src/components/StatusBadge.vue
Labels: 🎨 Design

#34 Style modal tab menu #31
  src/components/BaseModal.vue
  src/components/TabMenu.vue
  src/pages/MyPage.vue
Labels: 🎨 Design

#40 💄 style: 공통 컴포넌트인풋 버튼 드롭다운 퍼블리싱
  src/components/AppButton.vue
  src/components/Dropdown.vue
  src/components/IntroduceInput.vue
  src/components/NicknameInput.vue
  src/components/SearchInput.vue
Labels: 🎨 Design

#47 💄 style: 헤더 프로필 드롭다운 퍼블리싱
  src/layout/header/components/HeaderDropdown.vue
  src/layout/header/components/LoggedInRight.vue
Labels: 🎨 Design

#48 ✨ Feat: 마이페이지 퍼블리싱
  src/assets/icons/basic_profile.svg
  src/assets/icons/link_icon.svg
  src/assets/icons/profileEdit_icon.svg
  src/assets/icons/toggle_img.svg
  src/components/AppButton.vue
  src/components/TabMenu.vue
  src/pages/MyPage.vue
  src/pages/Mypage/MyPage.vue
  src/pages/Mypage/components/LargePostCard.vue
  src/pages/Mypage/components/MyBookmark.vue
  src/pages/Mypage/components/MyInfo.vue
  src/pages/Mypage/components/MyRecruitmentList.vue
  src/pages/Mypage/components/MyRequestList.vue
  src/router/index.js
  vite.config.js
Labels: ✨Feature

#52 style: 404 페이지 퍼블리싱
  index.html
  src/pages/ErrorPage.vue
  src/router/index.js
  src/styles/fonts.css
  src/styles/index.css
  src/styles/tailwind.css
  tailwind.config.js
Labels: 🎨 Design

#55 style: 글 목록 페이지 퍼블리싱
  src/assets/icons/index.js
  src/assets/icons/search_icon.vue
  src/components/FilterDropdown.vue
  src/components/PostCard.vue
  src/components/SearchInput.vue
  src/components/SkillSelectButton.vue
  src/constants/filter.js
  src/constants/skills/backend.js
  src/layout/MainLayout.vue
  src/pages/PostListPage.vue
  src/pages/PostListPage/PostListPage.vue
  src/pages/PostListPage/components/PostPagination.vue
  src/pages/PostListPage/components/SearchInput.vue
  src/pages/PostListPage/components/SkillFilterDropdown.vue
  src/router/index.js
  src/styles/tailwind.css
Labels: 🎨 Design

#59 🔨 refactor: 스킬 이미지 상수 관리 방식 변경
  src/assets/images/skills/index.js
  src/constants/filter.js
  src/constants/position.js
  src/constants/skill.js
  src/constants/skills/aos.js
  src/constants/skills/backend.js
  src/constants/skills/design.js
  src/constants/skills/devops.js
  src/constants/skills/frontend.js
  src/constants/skills/index.js
  src/constants/skills/ios.js
  src/constants/skills/marketing.js
  src/constants/skills/planning.js
  src/pages/EditProfilePage/components/ProfileSkills.vue
Labels: 🔨 Refactor

#57 style: 온보딩 페이지 퍼블리싱, 로그인 모달 전역 상태
  src/assets/images/onboard_left.png
  src/components/LoginModal.vue
  src/components/NicknameInput.vue
  src/components/PositionSelectButton.vue
  src/constants/filter.js
  src/layout/MainLayout.vue
  src/pages/OnboardPage.vue
  src/pages/OnboardPage/OnboardPage.vue
  src/pages/OnboardPage/components/OnboardStep1.vue
  src/pages/OnboardPage/components/OnboardStep2.vue
  src/pages/OnboardPage/components/OnboardTab.vue
  src/pages/OnboardPage/components/ProgressBar.vue
  src/router/index.js
  src/stores/loginModal.js
Labels: 🎨 Design, ✨Feature

#67 🎨 Style: 유저 상세 페이지 퍼블리싱
  src/components/AppButton.vue
  src/components/BaseModal.vue
  src/layout/MainLayout.vue
  src/pages/Mypage/components/LargePostCard.vue
  src/pages/Mypage/components/MyInfo.vue
  src/pages/Mypage/components/MyRequestList.vue
  src/pages/UserPage/UserPage.vue
  src/pages/UserPage/components/UserRecruitmentList.vue
  src/pages/UserPage/components/UserReviewList.vue
  src/router/index.js
  src/stores/baseModal.js
Labels: 🎨 Design

#73 style: 프로젝트 신청 모달 퍼블리싱
  src/components/BaseModal.vue
  src/components/LoginModal.vue
  src/pages/RecruitPostDetailPage.vue
  src/pages/RecruitPostDetailPage/RecruitPostDetailPage.vue
  src/pages/RecruitPostDetailPage/components/ApplyModal.vue
  src/router/index.js
Labels: 🎨 Design

#72 ✨ feat: 메인페이지 기능구현(포스트api연결, 좋아요+북마크버튼)
  package.json
  src/App.vue
  src/assets/images/loading.png
  src/components/PostCard.vue
  src/pages/MainPage.vue
  src/pages/MainPage/MainPage.vue
  src/pages/MainPage/components/MainSmallBanner.vue
  src/pages/MainPage/components/PostSection.vue
  src/pages/test_api_page_hw/LoginAndUserTest.vue
  src/router/index.js
  src/stores/user.js
  src/utils/.txt
  src/utils/useAuthAction.js
Labels: ✨Feature

#83 ✨feat: onboard
  jsconfig.json
  src/assets/images/onboard_icon.png
  src/components/BaseInput.vue
  src/components/BaseModal.vue
  src/components/LoginModal.vue
  src/components/PositionSelectButton.vue
  src/layout/header/HeaderLayout.vue
  src/layout/header/components/NonLoggedInRight.vue
  src/pages/MainPage.vue
  src/pages/OnboardPage/OnboardPage.vue
  src/pages/OnboardPage/components/OnboardAside.vue
  src/pages/OnboardPage/components/OnboardStep1.vue
  src/pages/OnboardPage/components/OnboardStep2.vue
  src/pages/OnboardPage/components/OnboardingCompleteModal.vue
Labels: ✨Feature

#85 fix: 프로필 이미지가 없을 시, 기본 프로필 이미지가 보여지도록 수정
  src/assets/icons/cancel_icon.vue
  src/assets/icons/link_icon.vue
  src/assets/icons/pencil_icon.vue
  src/assets/icons/plus_icon.vue
  src/assets/icons/search_icon.vue
  src/components/BaseInput.vue
  src/components/DropdownMenu.vue
  src/components/LoginModal.vue
  src/components/PositionSelectButton.vue
  src/components/SkillSelectButton.vue
  src/components/StatusBadge.vue
  src/constants/index.js
  src/pages/EditProfilePage/EditProfilePage.vue
  src/pages/EditProfilePage/components/DefaultInformation.vue
  src/pages/EditProfilePage/components/ProfileLinks.vue
  src/pages/EditRecruitPostPage/components/FristInfo/BasicInfoInput.vue
  src/pages/EditRecruitPostPage/components/thirdInfo/EditDetailInfo.vue
  src/pages/PostListPage/components/PostPagination.vue
  src/stores/profile.js
Labels: 🐞 Bug

#81 ✨ Feat: 상세페이지 퍼블리싱, 기능구현
  src/api/supabase/apply.js
  src/api/supabase/new_comment.js
  src/pages/RecruitPostDetailPage/RecruitPostDetailPage.vue
  src/pages/RecruitPostDetailPage/components/PostApplyList.vue
  src/pages/RecruitPostDetailPage/components/PostSideBar.vue
  src/pages/test_api_page_hw/LoginAndUserTest.vue
Labels: ✨Feature

#99 ✨ feat : 상세페이지 신청하기 버튼 applymodal연결
  src/api/supabase/apply.js
  src/pages/RecruitPostDetailPage/RecruitPostDetailPage.vue
  src/pages/RecruitPostDetailPage/components/ApplyModal.vue
  src/pages/RecruitPostDetailPage/components/PostApplyList.vue
  src/pages/RecruitPostDetailPage/components/PostSideBar.vue
Labels: ✨Feature

#101 Refactor: 온보딩 로직 개선 및 추가
  src/App.vue
  src/api/supabase/user.js
  src/pages/OnboardPage/OnboardPage.vue
  src/pages/OnboardPage/components/OnboardStep1.vue
  src/pages/OnboardPage/components/OnboardStep2.vue
  src/router/index.js
  src/styles/tailwind.css
Labels: ✨Feature, 🔨 Refactor

#100 🚨f ix: 마이페이지, 유저페이지 기능 수정
  public/logo.svg
  src/api/supabase/post.js
  src/pages/LoadingPage.vue
  src/pages/Mypage/MyPage.vue
  src/pages/Mypage/components/LargePostCard.vue
  src/pages/Mypage/components/MyBookmark.vue
  src/pages/Mypage/components/MyInfo.vue
  src/pages/Mypage/components/MyRecruitmentList.vue
  src/pages/Mypage/components/MyRequestList.vue
  src/pages/PostListPage/PostListPage.vue
  src/pages/UserPage/UserPage.vue
  src/pages/UserPage/components/UserRecruitmentList.vue
  src/utils/usePagination.js
Labels: 🐞 Bug, ✨Feature
